### ISSUE TITLE
Нет отображения изменений названия файла (sharing/code_update) при вторичной отправке кода

### ISSUE THREAD

**Issue by nikolaykosasha** [Hybusa/observer_java#3]
баг

**Comment by nikolaykosasha** [comment]
Описание: Нет отображения изменений названия файла (sharing/code_update) при вторичной отправке кода

Приоритет: High
Серьезность: S2
Предварительные условия:
Создать комнату
Подключиться к комнате

Шаги: 

1. Создать файл в проекте
2. Изменить название файла в проекте


Ожидаемый результат: При повторной передаче отображается изменение название файла
Фактический результат: При повторной передаче название файла передается без изменений названия

**Comment by Hybusa** [comment]
Кажется поправил. надо проверить
