### ISSUE TITLE
[BUG] Отсутсвует отправка события в IDE при создании папки в проекте

### ISSUE THREAD

**Issue by nikolaykosasha** [Hybusa/observer_java#32]
### Есть ли уже существующая проблема с этим?

- [X] Я искал(а) существующие проблемы

### Серьезность

Значительная ошибка, S3

### Приоритет

Medium

### Фактический результат

Папка создана в проекте, события нет 

### Ожидаемый результат

Папка создана, событие отправлено

### Шаги для воспроизведения

Предварительные условия: Подключиться к веб-приложению "Observer"

1. Создать папку в проекте

### Окружение

```markdown
- OS: MacOS: 12.7.3 (21H1015)
- Plugin: 1.2.15
```

### Есть ли что-то еще?

https://github.com/Hybusa/observer_java/assets/127039439/fa096cfb-4520-452f-be34-2b71222cabb2

**Comment by nikolaykosasha** [comment]
Событие отправляется только когда в папке создали новый файл

**Comment by Hybusa** [comment]
Это нормальное поведение

**Comment by nikolaykosasha** [comment]
Хорошо, закрываю Issues
